In [1]:
# magic function para hacer que los graficos de matplotlib se renderizen en el notebook.
%matplotlib inline

import datetime as datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('default') # haciendo los graficos un poco mas bonitos xD
plt.rcParams['figure.figsize'] = (15, 5)

## Basics

### Diference between series and dataframes

In [6]:
index = pd.date_range('1/1/2000', periods=8)
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [7]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a    0.359595
b    1.623140
c    0.155796
d   -0.862655
e   -0.905427
dtype: float64

In [8]:
s[:2]

a    0.359595
b    1.623140
dtype: float64

In [9]:
df = pd.DataFrame(np.random.randn(8, 3), index=index,columns=['A', 'B', 'C'])
df

A         B         C
2000-01-01  0.143558 -1.586764  0.200939
2000-01-02  1.095833 -0.474142  0.106075
2000-01-03 -0.070464  1.465861  0.110853
2000-01-04  0.376652  0.579555  0.342087
2000-01-05  0.875344  0.399077  0.853577
2000-01-06 -1.181598  0.955936 -0.559923
2000-01-07 -0.684131 -0.937714  0.862103
2000-01-08  1.128673  1.341980  1.203054

In [10]:
df.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [11]:
np.random.randn(8, 3)

array([[-0.85784751, -1.19610271, -0.03687068],
       [ 0.07152485, -0.25972376, -0.3123707 ],
       [-0.60037681,  1.82548217,  0.79679562],
       [ 0.9991054 ,  0.44719933, -0.33063323],
       [-1.14357462, -0.0264594 , -1.12712422],
       [ 0.54482261, -0.19078725,  0.294404  ],
       [-0.18782057, -0.64851981,  0.86496192],
       [ 1.83315801, -1.27498532,  1.42404799]])

In [14]:
df.ix[:,[1,2]]

B         C
2000-01-01 -1.586764  0.200939
2000-01-02 -0.474142  0.106075
2000-01-03  1.465861  0.110853
2000-01-04  0.579555  0.342087
2000-01-05  0.399077  0.853577
2000-01-06  0.955936 -0.559923
2000-01-07 -0.937714  0.862103
2000-01-08  1.341980  1.203054

In [11]:
wp = pd.Panel(np.random.randn(2, 5, 4), items=['Item1', 'Item2'],\
              major_axis=pd.date_range('1/1/2000', periods=5),\
              minor_axis=['A', 'B', 'C', 'D'])
wp

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 2000-01-01 00:00:00 to 2000-01-05 00:00:00
Minor_axis axis: A to D

### Attributes

In [17]:
df[:3]

A         B         C
2000-01-04  0.890492  0.602740 -0.023299
2000-01-05  0.770993 -0.048575  1.192550
2000-01-06 -2.536046  0.212527  1.142014
2000-01-07  0.196809 -0.945342 -0.072981
2000-01-08 -1.384615 -3.152787  1.019013

In [18]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [19]:
[x for x in df.columns]

['A', 'B', 'C']

In [21]:
df.values

array([[  3.87795416e-01,  -2.75151314e-01,   3.35347758e-01],
       [ -2.04431752e-03,   2.50429188e+00,  -9.14655087e-01],
       [ -6.32261820e-01,   9.39904289e-02,  -1.10173155e-01],
       [  8.90491587e-01,   6.02740024e-01,  -2.32986364e-02],
       [  7.70993244e-01,  -4.85750726e-02,   1.19255004e+00],
       [ -2.53604598e+00,   2.12526718e-01,   1.14201441e+00],
       [  1.96809361e-01,  -9.45341973e-01,  -7.29806036e-02],
       [ -1.38461485e+00,  -3.15278690e+00,   1.01901306e+00]])

In [22]:
s.values

array([ 0.36109584, -0.12898477, -1.81299416,  2.34146489, -0.10419526])

### Binary operations

In [23]:
df = pd.DataFrame({'one' : pd.Series(np.random.randn(3), index=['a', 'b', 'c']),\
                   'two' : pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),\
                   'three' : pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
df

one     three       two
a -0.956812       NaN -0.481334
b  0.252814 -0.007351  0.335352
c -0.781272  0.716216  1.129366
d       NaN -0.045235  0.367810

In [26]:
row = df.iloc[1]
row

one      0.252814
three   -0.007351
two      0.335352
Name: b, dtype: float64

In [32]:
df[1:2]

one     three       two
b  0.252814 -0.007351  0.335352

In [27]:
column = df['two']
column

a   -0.481334
b    0.335352
c    1.129366
d    0.367810
Name: two, dtype: float64

In [38]:
df['two'][:2]

a   -0.481334
b    0.335352
Name: two, dtype: float64

In [35]:
# to data level
df.isnull()

one  three    two
a  False   True  False
b  False  False  False
c  False  False  False
d   True  False  False

In [36]:
# to column level
df.isnull().any()

one       True
three     True
two      False
dtype: bool

In [37]:
# to column level
df.isnull().sum()

one      1
three    1
two      0
dtype: int64